# config.yaml
device: cuda
data:
  root: /path/to/data
  batch_size: 10
  num_workers: 4
  image_size: 128
  dataset: celeba
  transform:
    - name: Resize
      size: 128
    - name: RandomHorizontalFlip
    - name: ToTensor
    - name: Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
num_epochs: 1000
learning_rate: 0.0002
betas: [0.5, 0.999]
wandb:
  project: GenDet
  name: progan_generated_cat_fake_0001.png
log_freq: 10
